spring:
  security:
    filter:
      order: 10
  datasource:
    url: jdbc:h2:mem:blog
    username: blog
    password: blog
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true

jwt:
  secret: sAvqsvvCnRDgDJeLTyz3mDAFUvimklRacx1/wc5Rkdc=